# Generated by Django 5.1.3 on 2025-06-13 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('jobsapp', '0001_initial'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['-applied_at'], 'verbose_name': 'Applicant', 'verbose_name_plural': 'Applicants'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Favorite', 'verbose_name_plural': 'Favorites'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='website',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Applied At'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='applicants/cvs/', verbose_name='Resume/CV'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Reviewed'), (2, 'Interview Scheduled'), (3, 'Accepted'), (4, 'Rejected')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_favorites', to='jobsapp.job'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True, null=True, verbose_name='External Apply URL'),
        ),
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.CharField(blank=True, help_text='e.g., 2-5 years, Entry-level', max_length=100, null=True, verbose_name='Experience Required'),
        ),
        migrations.AlterField(
            model_name='job',
            name='filled',
            field=models.BooleanField(default=False, verbose_name='Is Filled'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Is Published'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('freelance', 'Freelance'), ('internship', 'Internship')], default='full-time', max_length=20, verbose_name='Job Type'),
        ),
        migrations.AlterField(
            model_name='job',
            name='last_date',
            field=models.DateField(blank=True, null=True, verbose_name='Application Deadline'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='jobs', to='tags.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Vacancies'),
        ),
    ]
