# Generated by Django 5.1.3 on 2025-06-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True, help_text='Optional: URL where users can apply on an external site.', null=True),
        ),
    ]
