# Generated by Django 5.1.3 on 2025-06-12 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0002_job_apply_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='cv',
            field=models.FileField(blank=True, help_text='Upload your resume/CV (PDF, DOCX).', null=True, upload_to='applicant_cvs/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1),
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
