# Generated by Django 5.1.3 on 2025-06-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsapp', '0002_alter_applicant_options_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Is Published'),
        ),
    ]
